apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sre-monitor
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: cluster2-placement
        requeueAfterSeconds: 30
  template:
    metadata:
      name: 'sre-monitor-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Sundeep-Soman/ocp-project.git   # <-- your repo
        targetRevision: main
        path: sre-monitor                                 # <-- folder path
      destination:
        server: '{{server}}'
        namespace: sre-monitor
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
