additionalTrustBundlePolicy: Proxyonly
apiVersion: v1
baseDomain: etcd.store
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  replicas: 0
  platform:
    aws:
      zones:
        - ap-south-1b  
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 1
  platform:
    aws:
      type: m6i.2xlarge
      zones:
        - ap-south-1b
metadata:
  name: cluster1
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    ipFamily: IPv4
    region: ap-south-1
    vpc: {}
publish: External
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfNjc3YTA1YjA2YTgwNGNmNDhhNzcxYjYzYTEyYWIxNDg6QkE5NVo3NEwyR1o5SFBEUUJaVTA5WldJNTRZN01OWlI2UlFUNFNRTVZYUkVBUTFINjBYRjFZMVUxOU8xNExROA==","email":"sundeepsomane@gmail.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfNjc3YTA1YjA2YTgwNGNmNDhhNzcxYjYzYTEyYWIxNDg6QkE5NVo3NEwyR1o5SFBEUUJaVTA5WldJNTRZN01OWlI2UlFUNFNRTVZYUkVBUTFINjBYRjFZMVUxOU8xNExROA==","email":"sundeepsomane@gmail.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTA0YzM0NzlmLThhMDYtNDJlNy1hMjNmLTI3OTYyODJhZTk2YTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmhPREl5Tm1JeVl6QXdNV1kwWlRFeFlXUXlZbU13T0dJeE9HVmtNR1UyWmlKOS5iRXZzSkRLUWNmMHNtanhhT0c3bURMUl9RQklQUUpSalJTVXEtNWY4M0xTUTdOYlhvX0FVbmJVMDB2Sm5INGh4M0Y3TUNTeWMyZXhqUTBwOTUxSEV6VnBVVHJnRE0wUWhEZFg4bWljcmlLWUxHSUF3ajZKbXV5eVJRTEp0b2RQUWdvWTRUR3Y1RU9FRkFIY05hS3RlOVdsVXp3RDVPd1pWenZpUTR5YUxzZFZPZVVYOWhEZGhsR0hQYkpHU2xobGd1LW5NMkxfQm1jT3VqakFiR0pzOFQzY3FJdG5zVE1DYkZQWW1fS3BLMjFtY0hkQ0VtLS1NNGhpTF9nYzJWM2NtdDdMVDBNYjVkNWx5LUN4QTRvS0tRTmZmWWMyR0Iwc0dYNWxybHBZeV9JenBhaHZ6X1NTTUNoaXFoT1FNVVh4S1BqVHZxc28xT2dUbE9JY0NfellCeWNEUFRidUFFT1N1SGt1X2ltaXpGbC1nN0htclkzY3hfNEhrSTk5OWJDQ2I3SmtZTGtlMkwwQWFoNGFCSEdyOWN0VmFBd0NTWUgwdy1Ka01rUUZIYmZKSzQtOGtHdjRScGpoVmRQNlhkd3R4aVRlcUU2anpCdzJoR1pfMUpOWkM3djFFWG9xTVFEcDdQbnZ3amlHRjJMdHYtbVpQV2kycEtqT0hHME5sd1pseVJ5ajJYLTNmWndqUzRGbEU0RmJZZ3ItbDZtV3hodld4RFlFcHc2SE5QZU5aVUlpQnpCaVpHYkc5cC10dWZsVmJRckFqMmp5bWRlYVlOZU9jbE5MWmtzQXk2aWFQU18yWFZnZkk1dFozeFktczN2dGM3aWhSNVJRMjkzRXV6bWtqWEJ1N1MxT05qSXF5MEtPS1Byd3p0VW1RQ2Y5M3NtTGttanZTbE5hc3ZNaw==","email":"sundeepsomane@gmail.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLTA0YzM0NzlmLThhMDYtNDJlNy1hMjNmLTI3OTYyODJhZTk2YTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmhPREl5Tm1JeVl6QXdNV1kwWlRFeFlXUXlZbU13T0dJeE9HVmtNR1UyWmlKOS5iRXZzSkRLUWNmMHNtanhhT0c3bURMUl9RQklQUUpSalJTVXEtNWY4M0xTUTdOYlhvX0FVbmJVMDB2Sm5INGh4M0Y3TUNTeWMyZXhqUTBwOTUxSEV6VnBVVHJnRE0wUWhEZFg4bWljcmlLWUxHSUF3ajZKbXV5eVJRTEp0b2RQUWdvWTRUR3Y1RU9FRkFIY05hS3RlOVdsVXp3RDVPd1pWenZpUTR5YUxzZFZPZVVYOWhEZGhsR0hQYkpHU2xobGd1LW5NMkxfQm1jT3VqakFiR0pzOFQzY3FJdG5zVE1DYkZQWW1fS3BLMjFtY0hkQ0VtLS1NNGhpTF9nYzJWM2NtdDdMVDBNYjVkNWx5LUN4QTRvS0tRTmZmWWMyR0Iwc0dYNWxybHBZeV9JenBhaHZ6X1NTTUNoaXFoT1FNVVh4S1BqVHZxc28xT2dUbE9JY0NfellCeWNEUFRidUFFT1N1SGt1X2ltaXpGbC1nN0htclkzY3hfNEhrSTk5OWJDQ2I3SmtZTGtlMkwwQWFoNGFCSEdyOWN0VmFBd0NTWUgwdy1Ka01rUUZIYmZKSzQtOGtHdjRScGpoVmRQNlhkd3R4aVRlcUU2anpCdzJoR1pfMUpOWkM3djFFWG9xTVFEcDdQbnZ3amlHRjJMdHYtbVpQV2kycEtqT0hHME5sd1pseVJ5ajJYLTNmWndqUzRGbEU0RmJZZ3ItbDZtV3hodld4RFlFcHc2SE5QZU5aVUlpQnpCaVpHYkc5cC10dWZsVmJRckFqMmp5bWRlYVlOZU9jbE5MWmtzQXk2aWFQU18yWFZnZkk1dFozeFktczN2dGM3aWhSNVJRMjkzRXV6bWtqWEJ1N1MxT05qSXF5MEtPS1Byd3p0VW1RQ2Y5M3NtTGttanZTbE5hc3ZNaw==","email":"sundeepsomane@gmail.com"}}}'
sshKey: |
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINdv7fMCYPLNdXEJ/dbeGxaA0Y4WFQhaR7AnY+M94BzQ ubuntu@ip-172-31-11-245
