apiVersion: apps/v1
kind: Deployment
metadata:
  name: eipo-ws-schedularservice
  namespace: eipo
spec:
  selector:
    matchLabels:
      app: eipo-ws-schedularservice
  template:
    metadata:
      labels:
        app: eipo-ws-schedularservice
        version: v1        
    spec:
      nodeSelector:
        node: backend
      serviceAccountName: eipo-sa
      automountServiceAccountToken: false
      containers:
        - name: eipo-ws-schedularservice
          image: geojit.azurecr.io/eipo-scheduler-service:Version-0.0.39
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL  
          ports:
          - containerPort: 8080       #6302-old
          resources:
            requests:
              memory: 300Mi
              cpu: 100m
            limits:
              memory: 1000Mi
              cpu: 2000m
          #livenessProbe:
          #  httpGet:
          #    path: /admin-service/health
          #    port: 6302
          #  initialDelaySeconds: 30
          #  periodSeconds: 30
          #  timeoutSeconds: 10
          #  failureThreshold: 3
          #readinessProbe:
          #  httpGet:
          #    path: /admin-service/health
          #    port: 6302
          #  initialDelaySeconds: 30
          #  periodSeconds: 30
          #  timeoutSeconds: 10
          #  failureThreshold: 3
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms256m -Xmx6g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:InitiatingHeapOccupancyPercent=40 -XX:+ParallelRefProcEnabled -XX:+ExplicitGCInvokesConcurrent -Dserver.tomcat.min-spare-threads=50 -Dserver.tomcat.threads.max=400"
            - name: TZ
              value: "Asia/Kolkata"
            - name: CATALINA_MAX_THREADS
              value: "400"
            - name: CATALINA_MIN_SPARE_THREADS
              value: "50"

            - name: SERVER_PROXY_IP
              value: "192.168.56.104"
            - name: SERVER_PROXY_PORT
              value: "3128"
            - name: SERVER_PROXY_ENABLE
              value: "true"
            - name: EIPO_SERVICE_BASE_URL
            # value: "http://eipo-ws-middleware-service.eipo.svc.cluster.local:8080/public/"
              value: "http://eipo-ws-middleware-service.eipo.svc.cluster.local:8080/ipoMiddleware/public/"
            - name: NOTIFICATION_SCHEDULAR_CRON
              value: "* * 9-10/1 12 * ?"
            - name: TRANSACTION_SCHEDULAR_CRON
              value: "* * 9-10/1 12 * ?"
            - name: MISMATCH_SCHEDULAR_CRON
              value: "* * 9-10/1 12 * ?"
            - name: MASTER_DATA_SCHEDULAR_CRON
              value: "* * 9-10/1 12 * ?"
            - name: NOTIFICATION_SCHEDULAR_CRON_INITDELAY
              value: "150000"
            - name: TRANSACTION_SCHEDULAR_CRON_INITDELAY
              value: "300000"
            - name: MISMATCH_SCHEDULAR_CRON_INITDELAY
              value: "450000"
            - name: MASTER_DATA_SCHEDULAR_CRON_INITDELAY
              value: "0"
            - name: NOTIFICATION_SERVICE_ENDPOINT
              value: "notifications/time/_get"
            - name: TRANSACTION_SERVICE_ENDPOINT
              value: "transactions/all/time/_get"
            - name: MISMATCH_SERVICE_ENDPOINT
              value: "transactions/mismatches/symbol/_get"
            - name: GET_SYMBOL_SERVICE_ENDPOINT
              value: "symbols/all/_get"
            - name: GET_MASTER_DATA_SERVICE_ENDPOINT
              value: "master/ipo/details/_get"
            - name: queue.order.schedular.cron
              value: "*/2 * 9-20 * * ?"
            - name: queue.order.schedular.cron.initdelay
              value: "600000"
            - name: queue.fetch.schedular.cron
              value: "0/5 * 10-16 * * ?"
            - name: transaction.queueorder.fetch.endpoint
              value: /transaction/queueorder/fetch/_post
              
          volumeMounts:
            - name: log-volume
              mountPath: /usr/local/middleware
            - name: log-volume-tmp
              mountPath: /tmp
      imagePullSecrets:
        - name: geojit-acr-secret
      volumes:
        - name: log-volume
          emptyDir: {}
        - name: log-volume-tmp
          emptyDir: {}
        
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: eipo-ws-schedularservice-hpa
  namespace: eipo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eipo-ws-schedularservice
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80  # Target CPU utilization percentage
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80  # Target memory utilization percentage

---
apiVersion: v1
kind: Service
metadata:
  name: eipo-ws-schedularservice-service
  namespace: eipo
  labels:
    app: eipo-ws-schedularservice
spec:
  selector:
    app: eipo-ws-schedularservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

